services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: wakfu-scraper-db
    restart: unless-stopped
    mem_limit: 1G
    volumes:
      - wakfu-scraper-db:/var/lib/postgresql:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      retries: 5
      timeout: 5s
      interval: 10s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wakfuscrap

volumes:
  wakfu-scraper-db:
    name: wakfu-scraper-db
    external: true