---
# Informations
info.app.environment: dev
spring.config.import:
  - "./libs/datasources.yaml"
  - "./libs/discord.yaml"
  - "./libs/wakfu.yaml"
  - "./libs/playwright.yaml"
  - "optional:./libs/.env[.properties]"

fumbus.logger:
  level:
    main: TRACE
    other: TRACE